### ISSUE TITLE
Conduct unit testing for Login function by JUnit

### ISSUE THREAD

**Issue by pmtam2010** [JoeFu/mseproject#10]
As a developer, I need to apply JUnit to test our Login functionality.

**Comment by JoeFu** [comment]
I think if you can you PHP to implement could be better, cheers.

**Comment by pmtam2010** [comment]
Move this issue to Icebox because it has low priority.

**Comment by pmtam2010** [comment]
This issue is closed because we didn't implement it due to time constraints and its low priority.
