### ISSUE TITLE
Move Data Query feature into new Dashboard user interface.

### ISSUE THREAD

**Issue by pmtam2010** [JoeFu/mseproject#160]
Clients agreed that the Data Query feature, which was developed on old Dashboard, needs be integrated into the new Dashboard user interface. The integration must include UI, business logics and APIs.

**Comment by pmtam2010** [comment]
Assign to Joe because he is responsible for integrating this feature with the new Dashboard

**Comment by JoeFu** [comment]
Fixed but not closed automatically.

**Comment by JoeFu** [comment]
Fixed but not closed automatically.
